#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.
i=1
while [ "$i" != 100 ]
do
	if [ $((i % 15)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
