#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.
filecheck="/etc/passwd"
fl1=""
fl2=""
fl3=""
while IFS= read -r line
do
	f1="$(echo "$line" | cut -d":" -f1)"
	f2="$(echo "$line" | cut -d":" -f4)"
	f3="$(echo "$line" | cut -d":" -f6)"
	f4="$(echo "$line" | cut -d":" -f7)"
	f5="$(echo "$line" | cut -d":" -f3)"
	f6="$(echo "$line" | cut -d":" -f2)"
	f7="$(echo "$line" | cut -d":" -f5)"
	echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$file_h"

