#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and:...
i=0
while [ "$i" != 12 ]
do
	j=1
	echo "Hour: $i"
	while [ "$j" != 60 ]
	do
		echo "$j"
		j=$((j + 1))
	done
	i=$((i + 1))
done
