#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.
fileCheck="school"
if [ -e "$fileCheck" ]
then
	echo "school file exists"
	if [ -s "$fileCheck" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$fileCheck" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
